runtime: nodejs10

handlers:
  - url: /favicon\.ico
    static_files: client/build/public/favicon.ico

  - url: /static
    static_dir: client/build/public

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
